src/Entity/TurnosPredefinidos.php
<?php

namespace App\Entity;

use App\Repository\TurnosPredefinidosRepository;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TurnosPredefinidosRepository::class)
 */
class TurnosPredefinidos
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="time")
     */
    private $hora_inicio;

    /**
     * @ORM\Column(type="time")
     */
    private $hora_Fin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHoraInicio(): ?DateTimeInterface
    {
        return $this->hora_inicio;
    }

    public function setHoraInicio(DateTimeInterface $hora_inicio): self
    {
        $this->hora_inicio = $hora_inicio;

        return $this;
    }

    public function getHoraFin(): ?DateTimeInterface
    {
        return $this->hora_Fin;
    }

    public function setHoraFin(DateTimeInterface $hora_Fin): self
    {
        $this->hora_Fin = $hora_Fin;

        return $this;
    }
}

src/Controller/TurnosPredefinidosController.php
<?php

namespace App\Controller;

use App\Entity\TurnosPredefinidos;
use App\Repository\TurnosPredefinidosRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/turnos/predefinidos", name="turnos_predefinidos_")
 */
class TurnosPredefinidosController extends AbstractController
{
    /**
     * @Route("/listar", name="listar")
     */
    public function index(TurnosPredefinidosRepository $predefinidosRepository): Response
    {
        $predefinidos = $predefinidosRepository->findAll();
        return $this->render('turnos_predefinidos/gestiona.html.twig', [
            'turnos' => $predefinidos
        ]);
    }

    /**
     * @Route("/get", name="datos")
     */
    public function recoger(TurnosPredefinidosRepository $predefinidosRepository): Response
    {
        $predefinidos = $predefinidosRepository->findAll();
        $horarios = array();

        foreach($predefinidos as $horario) {
            array_push($horarios, ["id" => $horario->getId(), "entrada" => $horario->getHoraInicio()->format("H:i"), "salida" => $horario->getHoraFin()->format("H:i")]);
        }
        return new JsonResponse($horarios);
    }

    /**
     * @Route("/crear", name="seccion_nueva")
     */
    public function gestionarSecciones(Request $request, TurnosPredefinidos $turno = null): Response
    {
        if ($request->isXMLHttpRequest()) {
            $content = $request->getContent();
            if (!empty($content)) {
                $params = json_decode($content, true);
                $inicio = new \Datetime(date('H:i', strtotime($params['HoraInicio'])));
                $fin = new \Datetime(date('H:i', strtotime($params['HoraFin'])));
                $em = $this->getDoctrine()->getManager();
                $turno = new TurnosPredefinidos();
                $turno->setHoraInicio($inicio);
                $turno->setHoraFin($fin);
                $em->persist($turno);
                $em->flush();
            }
            return new JsonResponse($turno->getId());
        }
        return new Response('Error!', 400);
    }

    /**
     * @Route("/eliminar/{id}", name="elemento_eliminar")
     */
    public function eliminar(Request $request, TurnosPredefinidosRepository $predefinidosRepository, $id): Response
    {
        if ($request->isXMLHttpRequest()) {
            $turno = $predefinidosRepository->findById($id);
            $this->getDoctrine()->getManager()->remove($turno);
            $this->getDoctrine()->getManager()->flush();
            return new JsonResponse(true);
        }
        return new Response('Error!', 400);
    }
}

templates/turnos_predefinidos/gestiona.html.twig
{% extends 'layout.html.twig' %}

{% block estilos %}
    <link rel="stylesheet" href="{{ asset('css/listados.css') }}">
    <link rel="stylesheet" href="{{ asset('css/tabla.css') }}">
    <link rel="stylesheet" href="{{ asset('css/creaTurnos.css') }}">
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/tabla.js') }}"></script>
    <script src="{{ asset('js/creaTurnos.js') }}"></script>
{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="listados_titulo">Turnos Predefinidos</h1>
        <div class="row">
            <div class="col">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div><h3 class="panel-title">Turnos</h3></div>
                        <div class="pull-right">
							<span class="clickable filter" data-toggle="tooltip" title="Toggle table filter"
                                  data-container="body">
								<i class="fas fa-filter"></i>
							</span>
                        </div>
                    </div>
                    <div class="panel-body">
                        <input type="text" class="form-control" id="dev-table-filter" data-action="filter"
                               data-filters="#dev-table" placeholder="Filtrar por inicio"/>
                    </div>
                    <div class="panel-table">
                        {% include 'turnos_predefinidos/predefinidos_tabla.partial.html.twig' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>

{% endblock %}

{% block title %}
    Gestión de usuarios
{% endblock %}

templates/turnos_predefinidos/predefinidos_tabla.partial.html.twig
<div class="creaTurnos_panel">
    <div class="creaTurnos_titulo">
        <h2>Crear nueva plantilla</h2>
    </div>
    <form>
        <div class="creaTurnos_inputs">

            <div><label>Desde: </label><input id="IN_TM_D" type="time" pattern="/[\S\s]+[\S]+/"></div>
            <div><label>Hasta: </label><input id="IN_TM_H" type="time" pattern="/[\S\s]+[\S]+/"></div>
        </div>
        <div>
            <button id="btnAceptar" type="button" class="btn btn-primary"><i class="fas fa-check"></i></button>
        </div>
    </form>

</div>
<table class="table table-hover" id="dev-table">
    <thead class="thead-dark">
    <tr>
        <th>Inicio</th>
        <th>Fin</th>
        <th></th>
    </tr>
    </thead>
    <tbody class="table-stripped panel_tabla_tupla_editar">
    <tr>
        <td colspan="2">Añadir nuevo turno</td>
        <td class="">
            <button id="btnCrea" class="btn btn-primary"><i class="fas fa-plus"></i></button>
        </td>
    </tr>
    {% for i in turnos %}
        <tr data-id="{{ i.id }}">
            <td>
                {{ i.horaInicio | format_time(locale='es', pattern="HH:mm") }}
            </td>
            <td>
                {{ i.horaFin | format_time(locale='es', pattern="HH:mm") }}
            </td>
            <td class="">
                <button class="btnBorrar btn btn-danger"><i class="fas fa-times-circle"></i></button>
            </td>
        </tr>
    {% endfor %}

    </tbody>
</table>